language: python

matrix:
  include:
  - dist: xenial
    os: linux
    language: python
    python: "3.5"
  - dist: xenial
    os: linux
    language: python
    python: "3.6"
  - dist: xenial
    os: linux
    language: python
    python: "3.8"
  
  - dist: trusty
    os: linux
    language: python
    python: "3.5"
  - dist: trusty
    os: linux
    language: python
    python: "3.6"
  - dist: trusty
    os: linux
    language: python
    python: "3.8"
    
  - dist: bionic
    os: linux
    language: python
    python: "3.5"
  - dist: bionic
    os: linux
    language: python
    python: "3.6"
  - dist: bionic
    os: linux
    language: python
    python: "3.8"


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

# command to run tests
script:
  - coverage run --source zoopt -m py.test
  - python example/simple_functions/quick_start.py
  
branches:
  only:
    - dev
    - master


after_success:
    - code_cov
